//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Assets {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Client.Assets.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Language:.
        /// </summary>
        public static string AppSettingsLanguage {
            get {
                return ResourceManager.GetString("AppSettingsLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process update delay:.
        /// </summary>
        public static string AppSettingsProcessDelay {
            get {
                return ResourceManager.GetString("AppSettingsProcessDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Company: .
        /// </summary>
        public static string ProcessViewCompanyNameDetailed {
            get {
                return ResourceManager.GetString("ProcessViewCompanyNameDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path: .
        /// </summary>
        public static string ProcessViewFileNameDetailed {
            get {
                return ResourceManager.GetString("ProcessViewFileNameDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Kill.
        /// </summary>
        public static string ProcessViewKill {
            get {
                return ResourceManager.GetString("ProcessViewKill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Name.
        /// </summary>
        public static string ProcessViewModuleName {
            get {
                return ResourceManager.GetString("ProcessViewModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File Name: .
        /// </summary>
        public static string ProcessViewModuleNameDetailed {
            get {
                return ResourceManager.GetString("ProcessViewModuleNameDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priority.
        /// </summary>
        public static string ProcessViewPriority {
            get {
                return ResourceManager.GetString("ProcessViewPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priority: .
        /// </summary>
        public static string ProcessViewPriorityDetailed {
            get {
                return ResourceManager.GetString("ProcessViewPriorityDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process Name.
        /// </summary>
        public static string ProcessViewProcessName {
            get {
                return ResourceManager.GetString("ProcessViewProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Process Name: .
        /// </summary>
        public static string ProcessViewProcessNameDetailed {
            get {
                return ResourceManager.GetString("ProcessViewProcessNameDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Name.
        /// </summary>
        public static string ProcessViewProductName {
            get {
                return ResourceManager.GetString("ProcessViewProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Product Name: .
        /// </summary>
        public static string ProcessViewProductNameDetailed {
            get {
                return ResourceManager.GetString("ProcessViewProductNameDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Version: .
        /// </summary>
        public static string ProcessViewProductVersionDetailed {
            get {
                return ResourceManager.GetString("ProcessViewProductVersionDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        public static string ProcessViewSearch {
            get {
                return ResourceManager.GetString("ProcessViewSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Time.
        /// </summary>
        public static string ProcessViewStartTime {
            get {
                return ResourceManager.GetString("ProcessViewStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start Time: .
        /// </summary>
        public static string ProcessViewStartTimeDetailed {
            get {
                return ResourceManager.GetString("ProcessViewStartTimeDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total CPU Usage Time.
        /// </summary>
        public static string ProcessViewTotalProcessorTime {
            get {
                return ResourceManager.GetString("ProcessViewTotalProcessorTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Total CPU Usage Time: .
        /// </summary>
        public static string ProcessViewTotalProcessorTimeDetailed {
            get {
                return ResourceManager.GetString("ProcessViewTotalProcessorTimeDetailed", resourceCulture);
            }
        }
    }
}
